export const possibleCountries = [
  {
    id: 121,
    name: 'Netherlands',
    code: 'NL',
    dialingCode: '+31',
    flag: '🇳🇱',
  },
  {
    id: 122,
    name: 'Spain',
    code: 'ES',
    dialingCode: '+34',
    flag: '🇪🇸',
  },
  {
    id: 123,
    name: 'United States',
    code: 'US',
    dialingCode: '+1',
    flag: '🇺🇸',
  },
  {
    id: 124,
    name: 'Mexico',
    code: 'MX',
    dialingCode: '+52',
    flag: '🇲🇽',
  },
  {
    id: 125,
    name: 'Germany',
    code: 'DE',
    dialingCode: '+49',
    flag: '🇩🇪',
  },
  {
    id: 126,
    name: 'Brazil',
    code: 'BR',
    dialingCode: '+55',
    flag: '🇧🇷',
  },
  {
    id: 127,
    name: 'France',
    code: 'FR',
    dialingCode: '+33',
    flag: '🇫🇷',
  },
  {
    id: 128,
    name: 'United Kingdom',
    code: 'GB',
    dialingCode: '+44',
    flag: '🇬🇧',
  },
  {
    id: 129,
    name: 'Italy',
    code: 'IT',
    dialingCode: '+39',
    flag: '🇮🇹',
  },
  {
    id: 130,
    name: 'Canada',
    code: 'CA',
    dialingCode: '+1',
    flag: '🇨🇦',
  },
];
